// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelTweak(arg1:string):Promise<void>;

export function CreateFolder(arg1:string,arg2:string):Promise<main.Folder>;

export function CreateNote(arg1:string,arg2:string):Promise<main.Note>;

export function DeleteFolder(arg1:string):Promise<void>;

export function DeleteNote(arg1:string):Promise<void>;

export function GetSettings():Promise<main.Settings>;

export function GetWorkspace():Promise<main.Workspace>;

export function RenameFolder(arg1:string,arg2:string):Promise<void>;

export function RenderMarkdown(arg1:string):Promise<string>;

export function SaveSettings(arg1:main.Settings):Promise<main.Settings>;

export function TestConnection(arg1:main.ApiConfig):Promise<string>;

export function TweakText(arg1:main.TweakRequest):Promise<string>;

export function UpdateNote(arg1:main.Note):Promise<main.Note>;
