// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFolder(arg1, arg2) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2);
}

export function CreateNote(arg1, arg2) {
  return window['go']['main']['App']['CreateNote'](arg1, arg2);
}

export function DeleteFolder(arg1) {
  return window['go']['main']['App']['DeleteFolder'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetWorkspace() {
  return window['go']['main']['App']['GetWorkspace']();
}

export function RenameFolder(arg1, arg2) {
  return window['go']['main']['App']['RenameFolder'](arg1, arg2);
}

export function RenderMarkdown(arg1) {
  return window['go']['main']['App']['RenderMarkdown'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function TweakText(arg1) {
  return window['go']['main']['App']['TweakText'](arg1);
}

export function UpdateNote(arg1) {
  return window['go']['main']['App']['UpdateNote'](arg1);
}
